---
title: "Week 4 Homework "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import library

```{r}
library(tidyverse)
library(here)
library(sf)
library(janitor)
library(dplyr)
library(tmap)
library(tmaptools)
```

## Import data

Author cant figure out how to use here package. lol

```{r}
report <- read_csv('/Users/yun/Documents/CASA/GIS/UCL_GIS_Week4_HW/Gender Inequality Index (GII).csv' , skip = 5,na = "..")
report <- head(report, -2)

report2 <- report %>% dplyr::select("Country", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019") %>% clean_names() %>% mutate(diff=x2019-x2010)

shape <- st_read('/Users/yun/Documents/CASA/GIS/UCL_GIS_Week4_HW/World_Countries_(Generalized)/World_Countries__Generalized_.shp') %>% clean_names()
```

## Join data

```{r}
map <- left_join(shape, report2, by = c("country" = "country"))

head(report2)
```

## Plot image

```{r pressure, echo=FALSE}
tmap_mode("plot")
qtm(map,fill ="diff")
```

```{r}
tmap_mode("view")

tm_shape(map) + 
  tm_polygons("x2010")
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
